spring:
  datasource:
    url: jdbc:mysql://localhost:13306/roadcode
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: roadcode

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.naver.com
    port: 465
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.naver.com

  data:
    redis:
      host: localhost
      port: 6379

  code:
    save-dir: /tmp/code-files
    save-file: "Solution"

#  docker:
#    python:
#      image: "python:3.11"
#      file-extension: ".py"
#      execute-command: "python /app/solution.py"
#    java:
#      image: "openjdk:17"
#      file-extension: ".java"
#      execute-command: "javac /app/Solution.java && java Solution"
#    c:
#      image: "gcc"
#      file-extension: ".c"
#      execute-command: "gcc /app/solution.c -o /app/solution && /app/solution"
#logging:
#  level:
#    org.springframework.mail: DEBUG