spring:
  custom:
    auth:
      allow-fixed-token: true

  datasource:
    url: jdbc:mysql://db-roadcode.ctw84yo0m2vd.ap-northeast-2.rds.amazonaws.com:3306/roadcode
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: roadcode

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.MYSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.trust: smtp.gmail.com

  data:
    redis:
      host: localhost
      port: 6379

  code:
    save-dir : /tmp/code-files
    save-file: "Solution"

  logging:
    level:
      org.springframework: INFO
      org.springframework.mail: DEBUG
      com.zaxxer.hikari: DEBUG

