spring:
  custom:
    auth:
      allow-fixed-token: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.trust: smtp.gmail.com

  data:
    redis:
      host: localhost
      port: 6379

  code:
    save-dir : C:/tmp/code-files
    save-file: "Solution"

  logging:
    level:
      org.springframework: INFO
      org.springframework.mail: DEBUG
      com.zaxxer.hikari: DEBUG
